/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mvc.Vista;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Carlo
 */
public class Interfaz_Producto extends javax.swing.JInternalFrame {

    /**
     * Creates new form Interfaz_Producto1
     */
    public Interfaz_Producto() {
        initComponents();
    }

    public JTextField getTxtBuscarTodo() {
        return txtBuscarTodo;
    }

    public void setTxtBuscarTodo(JTextField txtBuscarTodo) {
        this.txtBuscarTodo = txtBuscarTodo;
    }

    public JTable getTabla_producto() {
        return tabla_producto;
    }

    public void setTabla_producto(JTable tabla_producto) {
        this.tabla_producto = tabla_producto;
    }

    public JButton getBtn_Buscar() {
        return btn_Buscar;
    }

    public void setBtn_Buscar(JButton btn_Buscar) {
        this.btn_Buscar = btn_Buscar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MiDialogo = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_foto = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        btnFoto = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txt_catidad = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        PanelConsulta = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_producto = new javax.swing.JTable();
        txtBuscarTodo = new javax.swing.JTextField();
        brnAbrirGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        brnAbrirModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btn_Buscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btn_imprimir = new javax.swing.JButton();
        PanelCrear = new javax.swing.JPanel();
        dialogoInterfaz = new javax.swing.JLabel();
        panelColor = new javax.swing.JPanel();
        btn_salir = new javax.swing.JButton();

        MiDialogo.setResizable(false);
        MiDialogo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("ID:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("NOMBRE:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, -1));

        txt_nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 180, 26));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("PRECIO:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, -1));

        txt_precio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 70, 26));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("CANTIDAD:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 90, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("DESCRIPCION:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 120, -1));

        txt_foto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(txt_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 180, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("FOTOS:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 70, -1));
        jPanel1.add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 180, 26));

        btnFoto.setBackground(new java.awt.Color(102, 102, 0));
        btnFoto.setText("BUSCAR");
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });
        jPanel1.add(btnFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, -1, -1));

        imagen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 160, 170));

        btnGuardar.setBackground(new java.awt.Color(0, 102, 102));
        btnGuardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 100, -1));

        btnModificar.setBackground(new java.awt.Color(0, 102, 102));
        btnModificar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnModificar.setText("Modificar");
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 100, -1));

        btnCancelar.setBackground(new java.awt.Color(0, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 100, -1));
        jPanel1.add(txt_catidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 70, -1));

        txt_id.setEditable(false);
        txt_id.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 70, 26));

        MiDialogo.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 350));

        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelConsulta.setBackground(new java.awt.Color(102, 102, 0));
        PanelConsulta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_producto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tabla_producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "PRECIO", "CANTIDAD", "FOTO", "DESCRIPCION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla_producto);

        PanelConsulta.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 820, 240));

        txtBuscarTodo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtBuscarTodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarTodoKeyPressed(evt);
            }
        });
        PanelConsulta.add(txtBuscarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 139, -1));

        brnAbrirGuardar.setBackground(new java.awt.Color(0, 102, 102));
        brnAbrirGuardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        brnAbrirGuardar.setText("INGRESAR");
        PanelConsulta.add(brnAbrirGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 110, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscador:");
        PanelConsulta.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        brnAbrirModificar.setBackground(new java.awt.Color(0, 102, 102));
        brnAbrirModificar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        brnAbrirModificar.setText("MODIFICAR");
        PanelConsulta.add(brnAbrirModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 120, -1));

        btnEliminar.setBackground(new java.awt.Color(0, 102, 102));
        btnEliminar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        PanelConsulta.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 110, -1));

        btn_Buscar.setBackground(new java.awt.Color(0, 102, 102));
        btn_Buscar.setText("BUSCAR");
        PanelConsulta.add(btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(102, 102, 0));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mvc/Imagenes/cancel.png"))); // NOI18N
        btnLimpiar.setBorder(null);
        PanelConsulta.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 40, 30));

        btn_imprimir.setBackground(new java.awt.Color(0, 102, 102));
        btn_imprimir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_imprimir.setText("IMPRIMIR");
        PanelConsulta.add(btn_imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        getContentPane().add(PanelConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 340));

        PanelCrear.setBackground(new java.awt.Color(0, 102, 102));
        PanelCrear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dialogoInterfaz.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        dialogoInterfaz.setForeground(new java.awt.Color(255, 255, 255));
        dialogoInterfaz.setText("OFF");
        PanelCrear.add(dialogoInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        panelColor.setBackground(new java.awt.Color(255, 0, 0));
        PanelCrear.add(panelColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 30, 20));

        btn_salir.setBackground(new java.awt.Color(102, 102, 0));
        btn_salir.setText("SALIR");
        btn_salir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PanelCrear.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 70, 40));

        getContentPane().add(PanelCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 850, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarTodoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarTodoKeyPressed

    }//GEN-LAST:event_txtBuscarTodoKeyPressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFotoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        MiDialogo.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDialog MiDialogo;
    public javax.swing.JPanel PanelConsulta;
    public javax.swing.JPanel PanelCrear;
    public javax.swing.JButton brnAbrirGuardar;
    public javax.swing.JButton brnAbrirModificar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnFoto;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnModificar;
    public javax.swing.JButton btn_Buscar;
    public javax.swing.JButton btn_imprimir;
    public javax.swing.JButton btn_salir;
    public javax.swing.JLabel dialogoInterfaz;
    public javax.swing.JLabel imagen;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JPanel panelColor;
    public javax.swing.JTable tabla_producto;
    public javax.swing.JTextField txtBuscarTodo;
    public javax.swing.JTextField txt_catidad;
    public javax.swing.JTextField txt_descripcion;
    public javax.swing.JTextField txt_foto;
    public javax.swing.JTextField txt_id;
    public javax.swing.JTextField txt_nombre;
    public javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables
}
