/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mvc.Vista;

import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Carlo
 */
public class Interfaz_Factura extends javax.swing.JInternalFrame {

    /**
     * Creates new form Interfaz_Persona1
     */
    public Interfaz_Factura() {
        initComponents();
    }

    public JTable getTabla_factura() {
        return tabla_factura;
    }

    public void setTabla_factura(JTable tabla_factura) {
        this.tabla_factura = tabla_factura;
    }

    public JTextField getTxtBuscarTodo() {
        return txtBuscarTodo;
    }

    public void setTxtBuscarTodo(JTextField txtBuscarTodo) {
        this.txtBuscarTodo = txtBuscarTodo;
    }

    public JTextField getTxt_id_factura_detalle() {
        return txt_id_factura_detalle;
    }

    public void setTxt_id_factura_detalle(JTextField txt_id_factura_detalle) {
        this.txt_id_factura_detalle = txt_id_factura_detalle;
    }

    public JTable getTabla_detlle() {
        return tabla_detlle;
    }

    public void setTabla_detlle(JTable tabla_detlle) {
        this.tabla_detlle = tabla_detlle;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MiDialogo = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        txt_id_factura = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_cedula_cliente = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_total_factura = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_cliente = new javax.swing.JTable();
        txt_fecha_factura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btn_cancelar_Eliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        txt_id_factura_detalle = new javax.swing.JTextField();
        txt_id_producto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_total_detalle = new javax.swing.JTextField();
        btn_agregar_producto = new javax.swing.JButton();
        btn_listo = new javax.swing.JButton();
        txt_cantidad_detalle = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_detlle = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla_productos = new javax.swing.JTable();
        boton_calcular_total = new javax.swing.JButton();
        Reporte = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        txt_id_factura_reporte = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_cedula_cliente_reporte = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txt_total_factura_reporte = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txt_fecha_factura_reporte = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabla_reporte = new javax.swing.JTable();
        btn_salir_reporte = new javax.swing.JButton();
        PanelConsulta = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_factura = new javax.swing.JTable();
        txtBuscarTodo = new javax.swing.JTextField();
        brnAbrirGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        brnAbrirModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btn_Buscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        PanelCrear = new javax.swing.JPanel();
        dialogoInterfaz = new javax.swing.JLabel();
        panelColor = new javax.swing.JPanel();
        btn_salir = new javax.swing.JButton();

        MiDialogo.setResizable(false);
        MiDialogo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_id_factura.setEditable(false);
        txt_id_factura.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_id_factura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_id_factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 240, 26));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("FECHA:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, -1));

        txt_cedula_cliente.setEditable(false);
        txt_cedula_cliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_cedula_cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_cedula_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cedula_clienteKeyTyped(evt);
            }
        });
        jPanel1.add(txt_cedula_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 110, 26));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("TOTAL:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, -1));

        txt_total_factura.setEditable(false);
        txt_total_factura.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_total_factura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_total_factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 90, 26));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("CLIENTE:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 100, -1));

        tabla_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CEDULA", "NOMBRE", "APELLIDO"
            }
        ));
        jScrollPane1.setViewportView(tabla_cliente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 310, 190));

        txt_fecha_factura.setEditable(false);
        txt_fecha_factura.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_fecha_factura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_fecha_factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 150, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FACTURA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("ID FACTURA:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, -1));

        btnCancelar.setBackground(new java.awt.Color(102, 102, 0));
        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 120, 40));

        btnGuardar.setBackground(new java.awt.Color(102, 102, 0));
        btnGuardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGuardar.setText("GENERAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 120, 40));

        btn_cancelar_Eliminar.setBackground(new java.awt.Color(102, 102, 0));
        btn_cancelar_Eliminar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_cancelar_Eliminar.setText("CANCELAR");
        btn_cancelar_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar_EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancelar_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 120, 40));

        MiDialogo.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 310));

        jPanel2.setBackground(new java.awt.Color(102, 102, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DETALLE DE FACTURA");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TOTAL:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID FACTURA:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PRODUCTO:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CANTIDAD:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        txt_precio.setEditable(false);
        txt_precio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_precio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 50, -1));

        txt_id_factura_detalle.setEditable(false);
        txt_id_factura_detalle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_id_factura_detalle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txt_id_factura_detalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 240, -1));

        txt_id_producto.setEditable(false);
        txt_id_producto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_id_producto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txt_id_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 50, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PRECIO:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        txt_total_detalle.setEditable(false);
        txt_total_detalle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_total_detalle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txt_total_detalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 80, -1));

        btn_agregar_producto.setBackground(new java.awt.Color(0, 102, 102));
        btn_agregar_producto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_agregar_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mvc/Imagenes/agregar.png"))); // NOI18N
        btn_agregar_producto.setText("AGREGAR");
        jPanel2.add(btn_agregar_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 140, -1));

        btn_listo.setBackground(new java.awt.Color(0, 102, 102));
        btn_listo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_listo.setText("LISTO");
        jPanel2.add(btn_listo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 140, -1));
        jPanel2.add(txt_cantidad_detalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 50, -1));

        tabla_detlle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PRODUCTO", "CANTIDAD", "PRECIO", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_detlle.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tabla_detlleCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane3.setViewportView(tabla_detlle);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 580, 130));

        tabla_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "PRECIO", "CANTIDAD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabla_productos);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 270, 130));

        boton_calcular_total.setBackground(new java.awt.Color(102, 102, 0));
        boton_calcular_total.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mvc/Imagenes/moneda.png"))); // NOI18N
        jPanel2.add(boton_calcular_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 30, 20));

        MiDialogo.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 760, 310));

        Reporte.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_id_factura_reporte.setEditable(false);
        txt_id_factura_reporte.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_id_factura_reporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_id_factura_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 240, 26));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("FECHA:");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, -1));

        txt_cedula_cliente_reporte.setEditable(false);
        txt_cedula_cliente_reporte.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_cedula_cliente_reporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_cedula_cliente_reporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cedula_cliente_reporteKeyTyped(evt);
            }
        });
        jPanel3.add(txt_cedula_cliente_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 110, 26));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("TOTAL:");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, -1));

        txt_total_factura_reporte.setEditable(false);
        txt_total_factura_reporte.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_total_factura_reporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_total_factura_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 90, 26));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("CLIENTE:");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 100, -1));

        txt_fecha_factura_reporte.setEditable(false);
        txt_fecha_factura_reporte.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_fecha_factura_reporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txt_fecha_factura_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 150, 30));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("FACTURA");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, -1));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("ID FACTURA:");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, -1));

        Reporte.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 240));

        jPanel4.setBackground(new java.awt.Color(102, 102, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DETALLE DE FACTURA");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tabla_reporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PRODUCTO", "CANTIDAD", "PRECIO", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_reporte.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tabla_reporteCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane6.setViewportView(tabla_reporte);

        jPanel4.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 500, 150));

        btn_salir_reporte.setBackground(new java.awt.Color(0, 102, 102));
        btn_salir_reporte.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_salir_reporte.setText("SALIR");
        jPanel4.add(btn_salir_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 140, -1));

        Reporte.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 520, 250));

        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelConsulta.setBackground(new java.awt.Color(102, 102, 0));
        PanelConsulta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_factura.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tabla_factura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FECHA", "TOTAL", "CLIENTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla_factura);

        PanelConsulta.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 820, 240));

        txtBuscarTodo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtBuscarTodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarTodoKeyPressed(evt);
            }
        });
        PanelConsulta.add(txtBuscarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 139, -1));

        brnAbrirGuardar.setBackground(new java.awt.Color(0, 102, 102));
        brnAbrirGuardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        brnAbrirGuardar.setText("INGRESAR");
        PanelConsulta.add(brnAbrirGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 110, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscador:");
        PanelConsulta.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        brnAbrirModificar.setBackground(new java.awt.Color(0, 102, 102));
        brnAbrirModificar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        brnAbrirModificar.setText("REPORTE");
        PanelConsulta.add(brnAbrirModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 120, -1));

        btnEliminar.setBackground(new java.awt.Color(0, 102, 102));
        btnEliminar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        PanelConsulta.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 110, -1));

        btn_Buscar.setBackground(new java.awt.Color(0, 102, 102));
        btn_Buscar.setText("BUSCAR");
        PanelConsulta.add(btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(102, 102, 0));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mvc/Imagenes/cancel.png"))); // NOI18N
        btnLimpiar.setBorder(null);
        PanelConsulta.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 40, 30));

        getContentPane().add(PanelConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 340));

        PanelCrear.setBackground(new java.awt.Color(0, 102, 102));
        PanelCrear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dialogoInterfaz.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        dialogoInterfaz.setForeground(new java.awt.Color(255, 255, 255));
        dialogoInterfaz.setText("OFF");
        PanelCrear.add(dialogoInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        panelColor.setBackground(new java.awt.Color(255, 0, 0));
        PanelCrear.add(panelColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 30, 20));

        btn_salir.setBackground(new java.awt.Color(102, 102, 0));
        btn_salir.setText("SALIR");
        btn_salir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PanelCrear.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 70, 40));

        getContentPane().add(PanelCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 850, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarTodoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarTodoKeyPressed

    }//GEN-LAST:event_txtBuscarTodoKeyPressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tabla_detlleCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tabla_detlleCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla_detlleCaretPositionChanged

    private void txt_cedula_cliente_reporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cedula_cliente_reporteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cedula_cliente_reporteKeyTyped

    private void tabla_reporteCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tabla_reporteCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tabla_reporteCaretPositionChanged

    private void btn_cancelar_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelar_EliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txt_cedula_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cedula_clienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cedula_clienteKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDialog MiDialogo;
    public javax.swing.JPanel PanelConsulta;
    public javax.swing.JPanel PanelCrear;
    public javax.swing.JDialog Reporte;
    public javax.swing.JButton boton_calcular_total;
    public javax.swing.JButton brnAbrirGuardar;
    public javax.swing.JButton brnAbrirModificar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btn_Buscar;
    public javax.swing.JButton btn_agregar_producto;
    public javax.swing.JButton btn_cancelar_Eliminar;
    public javax.swing.JButton btn_listo;
    public javax.swing.JButton btn_salir;
    public javax.swing.JButton btn_salir_reporte;
    public javax.swing.JLabel dialogoInterfaz;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JPanel panelColor;
    public javax.swing.JTable tabla_cliente;
    public javax.swing.JTable tabla_detlle;
    public javax.swing.JTable tabla_factura;
    public javax.swing.JTable tabla_productos;
    public javax.swing.JTable tabla_reporte;
    public javax.swing.JTextField txtBuscarTodo;
    public javax.swing.JSpinner txt_cantidad_detalle;
    public javax.swing.JTextField txt_cedula_cliente;
    public javax.swing.JTextField txt_cedula_cliente_reporte;
    public javax.swing.JTextField txt_fecha_factura;
    public javax.swing.JTextField txt_fecha_factura_reporte;
    public javax.swing.JTextField txt_id_factura;
    public javax.swing.JTextField txt_id_factura_detalle;
    public javax.swing.JTextField txt_id_factura_reporte;
    public javax.swing.JTextField txt_id_producto;
    public javax.swing.JTextField txt_precio;
    public javax.swing.JTextField txt_total_detalle;
    public javax.swing.JTextField txt_total_factura;
    public javax.swing.JTextField txt_total_factura_reporte;
    // End of variables declaration//GEN-END:variables
}
