/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mvc.Vista;

import Mvc.Vista.*;
import Mvc.Controlador.Controlador_Persona;
import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;

/**
 *
 * @author Carlo
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal
     */
    public Menu_Principal() {
        initComponents();
    }

    public JMenuItem getBtnClientes() {
        return btnClientes;
    }

    public void setBtnClientes(JMenuItem btnClientes) {
        this.btnClientes = btnClientes;
    }

   

   

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DskPrincipal = new javax.swing.JDesktopPane();
        btn_persona = new javax.swing.JButton();
        btn_producto = new javax.swing.JButton();
        btn_factura = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnClientes = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        btnProducto = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btnFactura = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DskPrincipal.setBackground(new java.awt.Color(0, 102, 102));

        btn_persona.setBackground(new java.awt.Color(0, 102, 102));
        btn_persona.setForeground(new java.awt.Color(0, 102, 102));
        btn_persona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mvc/Imagenes/perfil.png"))); // NOI18N
        btn_persona.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_personaActionPerformed(evt);
            }
        });

        btn_producto.setBackground(new java.awt.Color(0, 102, 102));
        btn_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mvc/Imagenes/productos.png"))); // NOI18N
        btn_producto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btn_factura.setBackground(new java.awt.Color(0, 102, 102));
        btn_factura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mvc/Imagenes/factura.png"))); // NOI18N
        btn_factura.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TIENDA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 643, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(14, 14, 14))
        );

        DskPrincipal.setLayer(btn_persona, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DskPrincipal.setLayer(btn_producto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DskPrincipal.setLayer(btn_factura, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DskPrincipal.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DskPrincipalLayout = new javax.swing.GroupLayout(DskPrincipal);
        DskPrincipal.setLayout(DskPrincipalLayout);
        DskPrincipalLayout.setHorizontalGroup(
            DskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DskPrincipalLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btn_persona, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DskPrincipalLayout.setVerticalGroup(
            DskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DskPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_persona)
                    .addComponent(btn_producto)
                    .addComponent(btn_factura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 504, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Clientes");

        btnClientes.setText("ABRIR");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jMenu1.add(btnClientes);
        jMenu1.add(jSeparator1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Productos");

        btnProducto.setText("ABRIR");
        jMenu2.add(btnProducto);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reportes");

        btnFactura.setText("FACTURA");
        jMenu3.add(btnFactura);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ayuda");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DskPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DskPrincipal)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btn_personaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_personaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_personaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane DskPrincipal;
    public javax.swing.JMenuItem btnClientes;
    public javax.swing.JMenuItem btnFactura;
    public javax.swing.JMenuItem btnProducto;
    public javax.swing.JButton btn_factura;
    public javax.swing.JButton btn_persona;
    public javax.swing.JButton btn_producto;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
