/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mvc.Persona;

import Mvc.conexion.Conexion_Base_Datos;
import static com.sun.javafx.tk.Toolkit.getToolkit;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlo
 */
public class Interfaz_Persona extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Persona
     */
    public Interfaz_Persona() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MiDialogo = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_fecha_nacimiento = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        txt_foto = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        txt_sexo = new javax.swing.JComboBox<>();
        txt_sueldo = new javax.swing.JTextField();
        txt_cupo = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        btnFoto = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        txt_edad = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        PanelConsulta = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_personas = new javax.swing.JTable();
        txtBuscarTodo = new javax.swing.JTextField();
        brnAbrirGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        brnAbrirModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        PanelCrear = new javax.swing.JPanel();
        dialogoInterfaz = new javax.swing.JLabel();
        panelColor = new javax.swing.JPanel();

        MiDialogo.setResizable(false);
        MiDialogo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("CEDULA:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, -1));

        txt_cedula.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 180, 26));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("NOMBRE:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, -1));

        txt_nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 180, 26));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("APELLIDO:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 90, -1));

        txt_apellido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 180, 26));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("FECHA NACIMIENTO:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 160, -1));

        txt_fecha_nacimiento.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(txt_fecha_nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 150, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("EDAD:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 120, -1));

        btnCalcular.setBackground(new java.awt.Color(102, 102, 0));
        btnCalcular.setText("CALCULAR");
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 100, -1));

        txt_foto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(txt_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 180, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("FOTOS:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 70, -1));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("CORREO:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 70, -1));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("CUPO:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 70, -1));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("SUELDO:");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 70, -1));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("SEXO:");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 60, -1));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("TELEFONO:");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 90, -1));
        jPanel1.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 180, 26));

        txt_sexo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "MASCULINO", "FEMENINO", "OTRO" }));
        jPanel1.add(txt_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 180, -1));

        txt_sueldo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(txt_sueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 180, -1));

        txt_cupo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(txt_cupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 180, -1));

        txt_correo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 180, -1));

        btnFoto.setBackground(new java.awt.Color(102, 102, 0));
        btnFoto.setText("BUSCAR");
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });
        jPanel1.add(btnFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, -1, -1));

        imagen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 160, 170));

        btnGuardar.setBackground(new java.awt.Color(0, 102, 102));
        btnGuardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 100, -1));

        txt_edad.setEditable(false);
        txt_edad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_edad.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)));
        txt_edad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_edadMouseClicked(evt);
            }
        });
        jPanel1.add(txt_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 40, 26));

        btnModificar.setBackground(new java.awt.Color(0, 102, 102));
        btnModificar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnModificar.setText("Modificar");
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 100, -1));

        btnCancelar.setBackground(new java.awt.Color(0, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 100, -1));

        MiDialogo.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 350));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelConsulta.setBackground(new java.awt.Color(102, 102, 0));
        PanelConsulta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_personas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tabla_personas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CEDULA", "NOMBRES", "APELLIDOS", "FECHA NACIMIENTO", "TELEFONO", "SEXO", "SUELDO", "CUPO", "FOTO", "CORREO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla_personas);

        PanelConsulta.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 820, 250));

        txtBuscarTodo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtBuscarTodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarTodoKeyPressed(evt);
            }
        });
        PanelConsulta.add(txtBuscarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 139, -1));

        brnAbrirGuardar.setBackground(new java.awt.Color(0, 102, 102));
        brnAbrirGuardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        brnAbrirGuardar.setText("INGRESAR");
        PanelConsulta.add(brnAbrirGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 110, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscador:");
        PanelConsulta.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        brnAbrirModificar.setBackground(new java.awt.Color(0, 102, 102));
        brnAbrirModificar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        brnAbrirModificar.setText("MODIFICAR");
        PanelConsulta.add(brnAbrirModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 120, -1));

        btnEliminar.setBackground(new java.awt.Color(0, 102, 102));
        btnEliminar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        PanelConsulta.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 110, -1));

        getContentPane().add(PanelConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 340));

        PanelCrear.setBackground(new java.awt.Color(0, 102, 102));
        PanelCrear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dialogoInterfaz.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        dialogoInterfaz.setForeground(new java.awt.Color(255, 255, 255));
        dialogoInterfaz.setText("OFF");
        PanelCrear.add(dialogoInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        panelColor.setBackground(new java.awt.Color(255, 0, 0));
        PanelCrear.add(panelColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 30, 20));

        getContentPane().add(PanelCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 850, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarTodoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarTodoKeyPressed

        /*String[] titulos = {"ID", "NOMBRES","APELLIDOS","FECHA NACIMIENTO","TELEFONO","SEXO","SUELDO","CUPO","FOTO","CORREO"};
        Object[] registros = new Object[50];

        String sql = "SELECT * FROM clase.persona WHERE idpersona LIKE '%" + txtBuscarTodo.getText() + "%' "
                + "OR nombres LIKE '%" + txtBuscarTodo.getText() + "%'"
                + "OR apellidos LIKE '%" + txtBuscarTodo.getText() + "%'";

        DefaultTableModel model = new DefaultTableModel(null, titulos);
        Conexion_Base_Datos miconector = new Conexion_Base_Datos();
        Connection conect = miconector.ConectarBase();

        try {
            Statement st = (Statement) conect.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("idpersona");
                registros[1] = rs.getString("nombres");
                registros[2] = rs.getString("apellidos");
                //registros[3] = rs.getString("fechanacimiento");
                registros[4] = rs.getString("telefono");
                registros[5] = rs.getString("sexo");
                registros[6] = rs.getDouble("sueldo");
                registros[7] = rs.getInt("cupo");
                registros[8] = rs.getString("foto");
                registros[9] = rs.getString("correo");

                model.addRow(registros);
            }
            tabla_personas.setModel(model);
            miconector.close(conect);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }*/
    }//GEN-LAST:event_txtBuscarTodoKeyPressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        MiDialogo.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFotoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txt_edadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_edadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_edadMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDialog MiDialogo;
    public javax.swing.JPanel PanelConsulta;
    public javax.swing.JPanel PanelCrear;
    public javax.swing.JButton brnAbrirGuardar;
    public javax.swing.JButton brnAbrirModificar;
    public javax.swing.JButton btnCalcular;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnFoto;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnModificar;
    public javax.swing.JLabel dialogoInterfaz;
    public javax.swing.JLabel imagen;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel27;
    public javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JPanel panelColor;
    public javax.swing.JTable tabla_personas;
    public javax.swing.JTextField txtBuscarTodo;
    public javax.swing.JTextField txt_apellido;
    public javax.swing.JTextField txt_cedula;
    public javax.swing.JTextField txt_correo;
    public javax.swing.JTextField txt_cupo;
    public javax.swing.JTextField txt_edad;
    public com.toedter.calendar.JDateChooser txt_fecha_nacimiento;
    public javax.swing.JTextField txt_foto;
    public javax.swing.JTextField txt_nombre;
    public javax.swing.JComboBox<String> txt_sexo;
    public javax.swing.JTextField txt_sueldo;
    public javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
